spring:
  profiles:
    active: dev

---

#spring的配置
spring:
  application:
    name: springcloud-provider-dev
  profiles: dev

#eureka配置，服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
server:
  port: 8001

---
#spring的配置
spring:
  application:
    name: springcloud-provider-test
  profiles: test

#eureka配置，服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
server:
  port: 8002